### Package Imports

In [27]:
import numpy as np
from numpy.random import default_rng

# Assignment 1: Array Basics

Hi there,

Can you import Numpy and convert the following list comprehension (I just learned about comprehensions in an awesome course by Maven) into an array?

Once you've done that report the following about the array:
* The number of dimensions 
* The shape
* The number of elements in the array
* The type of data contained inside

In [8]:
my_list = [x * 10 for x in range(1, 11)]
array = np.array(my_list)
array

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [9]:
array.ndim

1

In [10]:
array.shape

(10,)

In [11]:
array.size

10

In [12]:
array.dtype

dtype('int64')

# Assignment 2: Array Creation

Thanks for your help with the first piece - I'm starting to understand some of the key differences between base Python data types and NumPy arrays. 

Does NumPy have anything like the range() function from base Python?

If so: 
* create the same array from assignment 1 using a NumPy function. 
* Make it 5 rows and 2 columns. 
* It's ok if the datatype is float or int.

In [23]:
new_array = np.linspace(10, 100, 10)
new_array

array([ 10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [24]:
new_array.reshape(5, 2)

array([[ 10.,  20.],
       [ 30.,  40.],
       [ 50.,  60.],
       [ 70.,  80.],
       [ 90., 100.]])

Looking good so far! One of our data scientists asked about random number generation in NumPy.

Can you create a 3x3 array of random numbers between 0 and 1? Use a random state of 2022.

Store the random array in a variable called `random_array`.

In [14]:
random_array = np.random.random((1, 3, 3))
random_array

array([[[0.28123321, 0.36377033, 0.21682198],
        [0.78316277, 0.36311419, 0.69959623],
        [0.31096912, 0.18640881, 0.62759364]]])

In [30]:
# Using random state of 2022
rng = default_rng(2022)
random_array = rng.random(9).reshape(3, 3)
random_array

array([[0.24742606, 0.09299006, 0.61176337],
       [0.06066207, 0.66103343, 0.75515778],
       [0.1108689 , 0.04305584, 0.41441747]])

# Assignment 3: Accessing Array Data


Slice and index the `random_array` we created in the previous exercise. Perform the following:

* Grab the first two 'rows' of the array
* Grab the entire first column
* Finally, grab the second selement of the third row.

Thanks!


In [31]:
random_array[:2, :]

array([[0.24742606, 0.09299006, 0.61176337],
       [0.06066207, 0.66103343, 0.75515778]])

In [32]:
random_array[:, :1]

array([[0.24742606],
       [0.06066207],
       [0.1108689 ]])

In [33]:
random_array[1, 2]

0.7551577777762973

In [15]:
random_array = np

# Assignment 4: Arithmetic Operations

The creativity of our marketing team knows no bounds!

They've asked us to come up with a simple algorithm to provide a random discount to our list of prices below. 

Before we do that, 

* Add a 5 dollar shipping fee to each price. Call this array `total`.

Once we have that, we want to use the random_array created in assignment 2 and apply them to the 6 prices.

* Grab the first 6 numbers from `random_array`, reshape it to one dimension. Call this `discount_pct`.
* Subtract `discount_pct` FROM 1, store this in `pct_owed`.
* Multiply `pct_owed` by `total` to get the final amount owed.

In [45]:
prices = np.array([5.99, 6.99, 22.49, 99.99, 4.99, 49.99])


In [46]:
total = prices + 5

In [47]:
total

array([ 10.99,  11.99,  27.49, 104.99,   9.99,  54.99])

In [56]:
discount_pct = random_array[:2, :].reshape(6)
pct_owed = 1 - discount_pct
final_owd = total * pct_owed

In [57]:
print(discount_pct)
print(pct_owed)
print(final_owd.round(2))

[0.24742606 0.09299006 0.61176337 0.06066207 0.66103343 0.75515778]
[0.75257394 0.90700994 0.38823663 0.93933793 0.33896657 0.24484222]
[ 8.27 10.88 10.67 98.62  3.39 13.46]


# Assignment 5: Filtering Arrays

Filter the product array to only include those with prices greater than 25.

Modify your logic to include cola, despite it not having a price greater than 25. 
Store the elements returned in an array called `fancy_feast_special`.

Next, create a shipping cost array where the cost is 0 if price is greater than 20, and 5 if not. 

In [17]:
products = np.array(
    ["salad", "bread", "mustard", "rare tomato", "cola", "gourmet ice cream"]
)

products

array(['salad', 'bread', 'mustard', 'rare tomato', 'cola',
       'gourmet ice cream'], dtype='<U17')

In [61]:
fancy_feast_special = products[(prices > 25) | (products == 'cola')]
fancy_feast_special

array(['rare tomato', 'cola', 'gourmet ice cream'], dtype='<U17')

In [65]:
shipping = np.where(prices > 20, 0, 5)
shipping

array([5, 5, 0, 0, 5, 0])

# Assignment 6: Aggregating and Sorting Arrays

First, grab the top 3 highest priced items in our list. 

Then, calculated the mean, min, max, and median of the top three prices.

Finally, calculate the number of unique price tiers in our `price_tiers` array.

In [66]:
prices = np.array([5.99, 6.99, 22.49, 99.99, 4.99, 49.99])
prices

array([ 5.99,  6.99, 22.49, 99.99,  4.99, 49.99])

In [19]:
price_tiers = np.array(["budget", "budget", "mid-tier", "luxury", "mid-tier", "luxury"])

In [67]:
prices.sort()
prices

array([ 4.99,  5.99,  6.99, 22.49, 49.99, 99.99])

In [68]:
top3 = prices[-3:]
top3

array([22.49, 49.99, 99.99])

In [69]:
np.unique(price_tiers)

array(['budget', 'luxury', 'mid-tier'], dtype='<U8')

# Assignment 7: Bringing it All Together

Ok, final NumPy task - let's read in some data with the help of Pandas.

Our data scientist provided the code to read in a csv as a Pandas dataframe, and has converted the two columns of interest to arrays.

* Filter `sales_array` down to only sales where the product family was produce. 

* Then, randomly sample roughly half (random number < .5) of the produce sales and report the mean and median sales. Use a random seed of 2022.

* Finally, create a new array that has the values 'above_both', 'above_median', and 'below_both' based on whether the sales were above the median and mean of the sample, just above the median of the sample, or below both the median and mean of the sample. 

In [73]:
import pandas as pd
import numpy as np

retail_df = pd.read_csv("retail/retail_2016_2017.csv",
                        skiprows=range(1, 11000),
                        nrows=1000)

family_array = np.array(retail_df["family"])
sales_array = np.array(retail_df["sales"])

In [74]:
produce_array = sales_array[family_array == "PRODUCE"]

In [75]:
rng = np.random.default_rng(2022)

In [76]:
random_array = rng.random(30)
random_array

array([0.24742606, 0.09299006, 0.61176337, 0.06066207, 0.66103343,
       0.75515778, 0.1108689 , 0.04305584, 0.41441747, 0.98862926,
       0.96919869, 0.25697153, 0.55876211, 0.24234798, 0.32202029,
       0.89135975, 0.94611366, 0.72253931, 0.92847437, 0.99608701,
       0.2494223 , 0.06229007, 0.94479027, 0.65028587, 0.32167568,
       0.08336384, 0.21924361, 0.08417791, 0.05213927, 0.20525022])

In [80]:
sampled_array = produce_array[random_array < 0.5]

In [86]:
mean = sampled_array.mean()
mean

2268.102470588235

In [84]:
median = np.median(sampled_array)
median

1272.755

In [94]:
max_val_med_mean = ""
if median < mean:
    max_val_med_mean = "above_median" 
else:
    max_val_med_mean = "above_mean"
np.where(
    sampled_array < min(median, mean),
    "bellow_both",
    np.where(sampled_array > max(median, mean), "above_both", max_val_med_mean)
)

array(['above_median', 'bellow_both', 'bellow_both', 'bellow_both',
       'above_both', 'bellow_both', 'bellow_both', 'above_both',
       'bellow_both', 'above_median', 'above_both', 'above_both',
       'bellow_both', 'above_median', 'above_both', 'bellow_both',
       'above_both'], dtype='<U12')

In [88]:
sampled_array

array([1662.394,  447.064,  962.866, 1077.44 , 3404.531,  962.96 ,
       1089.319, 7860.031,  446.038, 1272.755, 2775.771, 2339.906,
        722.333, 1567.843, 2458.456,  673.885, 8834.15 ])